include:
  - local: .gitlab/ci/lint.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/quality.yml
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/deploy.yml

stages:
  - lint
  - test
  - quality
  - smoke
  - build
  - deploy

variables:
  HARBOR_REGISTRY: harbor.example.com
  HARBOR_PROJECT: propriateraydb
  REGISTRY: $HARBOR_REGISTRY/$HARBOR_PROJECT
  IMAGE_FRONTEND: $REGISTRY/frontend
  IMAGE_BACKEND: $REGISTRY/backend
  CI_TOOLS_IMAGE: $REGISTRY/ci-tools:ubi9
  BUILDAH_IMAGE: quay.io/buildah/stable:v1.43.1
  SONAR_SCANNER_IMAGE: sonarsource/sonar-scanner-cli:5.0.1
  OPENSHIFT_NAMESPACE: propriateraydb
