sonar.projectName=PropriaterayDB Web Service
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.scannerwork/**,backend/package-lock.json
sonar.coverage.exclusions=frontend/**,backend/src/types/**
sonar.typescript.tsconfigPaths=backend/tsconfig.json
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
