frontend:
  replicas: 1
  route:
    enabled: true

backend:
  replicas: 1
  auth:
    mode: oidc
    sessionStore: redis
  config:
    nodeEnv: production
    logLevel: debug

mariadb:
  enabled: true
  persistence:
    storage: 5Gi

redis:
  enabled: true
  persistence:
    enabled: false
