apiVersion: v1
kind: Secret
metadata:
  name: {{ include "propriateraydb.fullname" . }}-backend-secrets
  labels:
    {{- include "propriateraydb.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.mariadb.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  SESSION_SECRET: {{ .Values.backend.secrets.sessionSecret | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.backend.secrets.oidcClientSecret | quote }}
