apiVersion: v1
kind: Service
metadata:
  name: {{ include "propriateraydb.fullname" . }}-backend
  labels:
    {{- include "propriateraydb.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "propriateraydb.componentLabels" (dict "component" "backend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
