apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "propriateraydb.fullname" . }}-frontend
  labels:
    {{- include "propriateraydb.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "propriateraydb.componentLabels" (dict "component" "frontend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "propriateraydb.componentLabels" (dict "component" "frontend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "propriateraydb.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      containers:
        - name: frontend
          image: {{ include "propriateraydb.frontendImage" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
