{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "propriateraydb.fullname" . }}-mariadb-secrets
  labels:
    {{- include "propriateraydb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mariadb.database | quote }}
  MYSQL_USER: {{ .Values.mariadb.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.password | quote }}
{{- end }}
