{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "propriateraydb.fullname" . }}-redis
  labels:
    {{- include "propriateraydb.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "propriateraydb.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "propriateraydb.componentLabels" (dict "component" "redis" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "propriateraydb.componentLabels" (dict "component" "redis" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.redis.persistence.storageClassName }}
        storageClassName: {{ .Values.redis.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.storage }}
  {{- end }}
{{- end }}
